package com.raoqiang.phoenix.calculate.constant;

public class DropIndex {

    public static final String[] APPLICATION_DROP_INDEX= {
            "CNT_CHILDREN", "CNT_FAM_MEMBERS", "HOUR_APPR_PROCESS_START",
            "FLAG_EMP_PHONE", "FLAG_MOBIL", "FLAG_CONT_MOBILE", "FLAG_EMAIL", "FLAG_PHONE",
            "FLAG_OWN_REALTY", "REG_REGION_NOT_LIVE_REGION", "REG_REGION_NOT_WORK_REGION",
            "REG_CITY_NOT_WORK_CITY", "OBS_30_CNT_SOCIAL_CIRCLE", "OBS_60_CNT_SOCIAL_CIRCLE",
            "AMT_REQ_CREDIT_BUREAU_DAY", "AMT_REQ_CREDIT_BUREAU_MON", "AMT_REQ_CREDIT_BUREAU_YEAR",
            "COMMONAREA_MODE", "NONLIVINGAREA_MODE", "ELEVATORS_MODE", "NONLIVINGAREA_AVG",
            "FLOORSMIN_MEDI", "LANDAREA_MODE", "NONLIVINGAREA_MEDI", "LIVINGAPARTMENTS_MODE",
            "FLOORSMIN_AVG", "LANDAREA_AVG", "FLOORSMIN_MODE", "LANDAREA_MEDI",
            "COMMONAREA_MEDI", "YEARS_BUILD_AVG", "COMMONAREA_AVG", "BASEMENTAREA_AVG",
            "BASEMENTAREA_MODE", "NONLIVINGAPARTMENTS_MEDI", "BASEMENTAREA_MEDI",
            "LIVINGAPARTMENTS_AVG", "ELEVATORS_AVG", "YEARS_BUILD_MEDI", "ENTRANCES_MODE",
            "NONLIVINGAPARTMENTS_MODE", "LIVINGAREA_MODE", "LIVINGAPARTMENTS_MEDI",
            "YEARS_BUILD_MODE", "YEARS_BEGINEXPLUATATION_AVG", "ELEVATORS_MEDI", "LIVINGAREA_MEDI",
            "YEARS_BEGINEXPLUATATION_MODE", "NONLIVINGAPARTMENTS_AVG", "HOUSETYPE_MODE",
            "FONDKAPREMONT_MODE", "EMERGENCYSTATE_MODE", "FLAG_DOCUMENT_2", "FLAG_DOCUMENT_4",
            "FLAG_DOCUMENT_5", "FLAG_DOCUMENT_6", "FLAG_DOCUMENT_7", "FLAG_DOCUMENT_9",
            "FLAG_DOCUMENT_10", "FLAG_DOCUMENT_11", "FLAG_DOCUMENT_12", "FLAG_DOCUMENT_13", "FLAG_DOCUMENT_14",
            "FLAG_DOCUMENT_15", "FLAG_DOCUMENT_16", "FLAG_DOCUMENT_17", "FLAG_DOCUMENT_19",
            "FLAG_DOCUMENT_20", "FLAG_DOCUMENT_21"
    };

}
